### ISSUE TITLE
Source reorganization

### ISSUE THREAD

**Issue by XhmikosR** [pattle/simpsons-in-css#2]
Hi.

What do you think about moving the CSS in src, remove vendor prefixes, add grunt with autoprefixer, csslint etc etc and output the CSS in the /css directory? This will improve things a lot. You won't need to care about vendor prefixes, we can validate HTML/CSS and much more.

If you are interested I can provide a PR for this.

**Comment by tenhobi** [comment]
I recommend Gulp instead. Autoprefixer would be really useful for this project!
