### ISSUE TITLE
To develop for the web, not for Google

### ISSUE THREAD

**Issue by Flaburgan** [pattle/simpsons-in-css#35]
First of all, thanks for your awesome work.

> (Best viewed in Chrome)

I opened your page both in Firefox and Chrome and I see **no difference**. The web is the platform, to develop for a specific render engine is dangerous, because we are going to reproduce the IE6 nightmare. Especially here, where the website doesn't use any specific technology and is fully functional on different modern browsers.

Please drop the "Best viewed in Chrome" indication. (I would have done it in a pull request but didn't find it on this repo, I guess the presentation page is not here).

**Comment by webatou** [comment]
I agree with Flaburgan of course, so I really would like to know why you say (Best viewed in Chrome), while this is not the case.

**Comment by taratatach** [comment]
Great work by the way! I didn't we could do stuff like this with sheer CSS :O

**Comment by pattle** [comment]
You're right @Flaburgan 

I did this a while ago but forgot to close this issue
